MONGODB_HOST: mongodb-{{ env }}.manikumar.online
REDIS_HOST: redis-{{ env }}.manikumar.online
MYSQL_HOST: mysql-{{ env }}.manikumar.online 
RABBITMQ_HOST: rabbitmq-{{ env }}.manikumar.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.manikumar.online
USER_HOST: user.backend-alb-{{ env }}.manikumar.online
CART_HOST: cart.backend-alb-{{ env }}.manikumar.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.manikumar.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.manikumar.online









