MONGODB_HOST: mongodb-{{ env }}.manikumar.online
REDIS_HOST  : redis-{{ env }}.manikumar.online
MYSQL_HOST: mysql-{{ env }}.manikumar.online
RABBITMQ_HOST: rabbitmq-{{ env }}.manikumar.online 
CATALOGUE_HOST: catalogue-{{ env }}.manikumar.online
USER_HOST: user-{{ env }}.manikumar.online
CART_HOST: cart-{{ env }}.manikumar.online
SHIPPING__HOST: shipping-{{ env }}.manikumar.online
PAYMENT_HOST: payment-{{ env }}.manikumar.online










